<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Light" Id="{51c482b5-784f-436d-9476-aaf7d405233d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Light
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Light">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>