<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8d51e464-d0c5-46d7-9c54-d879937b15ac}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	output1: BOOL;
	input1 : BOOL;
	andrew : dword;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>